name: macOS

on:
  push:
    branches:
      - main
    paths:
      - "uvio/**"
  pull_request:
    branches:
      - main
    paths:
      - "uvio/**"

jobs:
  build_macos:
    runs-on: macos-latest
    strategy:
      fail-fast: false
    name: "Apple clang (C++20, release)"
    env:
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup
        run: |
          # brew install curl git pkg-config llvm
          brew install curl git pkg-config

      - name: Setup Python
        uses: actions/setup-python@main
        with:
          python-version: '3.12'

      - name: Install Meson/Ninja
        run: |
          python3 -m pip install meson ninja

      - name: Build
        run: |
          meson setup build -Dbuildtype=release
          meson compile -C build
          ./build/tests/test_latch
          ./build/tests/test_coredump
          ./build/tests/gtests/all_gtests

      - name: Install
        run: |
          sudo meson install -C build
