name: Windows

on:
  push:
    branches:
      - main
    paths:
      - "uvio/**"
  pull_request:
    branches:
      - main
    paths:
      - "uvio/**"

jobs:
  build_macos:
    runs-on: windows-latest
    strategy:
      fail-fast: false
    name: "MSVC (C++20, release)"
    steps:
      - name: Checkout
        uses: actions/checkout@main

      # - name: Setup Python
      #   uses: actions/setup-python@main
      #   with:
      #     python-version: '3.12'

      - name: Install dependencies
        run: |
          vcpkg install libuv:x64-windows

      - name: Prepare msvc toolchain
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Install Meson/Ninja
        run: |
          python3 -m pip install meson ninja

      - name: Build
        run: |
          meson setup build -Dbuildtype=release
          meson compile -C build
          # ./build/tests/gtests/all_gtests
          .\build\tests\gtests\all_gtests.exe

      - name: Install
        run: |
          meson install -C build
